# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db33edcbdc29aa94ae596f436c2b31b97ad1325f4b1d6d6f4ca3110b6eaa8608bf2792e74198a09138454eb2e657e68b7f043449062995bc71a85e91ff9f1cd7

test:
  secret_key_base: 659d8303484c78fddf7f6ae384edfff0a69755faa0106c5ab708aefa913abe2c71f68bc4b8c1cfd9379b6dc8644fc79ec619f892eeb29c271019ae849c4ac766

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
